### filtaviams town
GET http://localhost:3000/api/ads/filter?town=Vilnius

### filtaviams type
GET http://localhost:3000/api/ads/filter?type=sell

### filtaviams price
GET http://localhost:3000/api/ads/filter?price=300

### filtaviams price
GET http://localhost:3000/api/ads/filter?category=Automobiliai

### filtaviams visu
GET http://localhost:3000/api/ads/filter?town=Vilnius&category=Nekilnojamas turtas&price=3000.00&type=buy

### Gauti visus skelbimus(publikuotus)
GET http://localhost:3000/api/ads

### Gauti visus skelbimus(publikuotus)
GET http://localhost:3000/api/ads/user/id/1

### Gauti visus skelbimus 404
GET http://localhost:3000/api/4004

### Gauti viena skelbima pagal jo id(publikuotas)
GET http://localhost:3000/api/ads/1

### Sukurti skelbima
POST http://localhost:3000/api/ads
Content-Type: application/json

{
  "title": "Parduodu automobilį",
  "description": "Automobilis labai geros būklės",
  "price": 5000,
  "main_image_url": "mainCar.jpg",
  "phone": "+37060000000",
  "type": "sell",
  "user_id": 2,
  "town_id": 4,
  "category_id": 6
}

### Istrinti viena skelbima
DELETE http://localhost:3000/api/ads/1
