### filtaviams
GET http://localhost:3000/api/ads/filter?town=Vilnius
### filtaviams
GET http://localhost:3000/api/ads/filter?type=sell

### filtaviams visu
GET http://localhost:3000/api/ads/filter?town=Vilnius&category=Automobiliai

### Gauti visus skelbimus(publikuotus/nepublikuotus)
GET http://localhost:3000/api/ads

### Gauti visus skelbimus 404
GET http://localhost:3000/api/4004

### Gauti viena skelbima pagal jo id(publikuotus/nepublikuotus)
GET http://localhost:3000/api/ads/1

### Sukurti skelbima
POST http://localhost:3000/api/ads
Content-Type: application/json

{
  "title": "Parduodu vaikišką lovytę",
  "description": "Lovyte beveik kaip nauja, yra keli įbrėžimai",
  "price": 40,
  "phone": "+3709998889",
  "TYPE": "sell"
}

### Istrinti viena skelbima
DELETE http://localhost:3000/api/ads/1
