### Gauti visus skelbimus(publikuotus)
GET http://localhost:3000/api/ads/filter?townId=1

### Gauti visus skelbimus(publikuotus)
GET http://localhost:3000/api/ads

### Gauti visus skelbimus 404
GET http://localhost:3000/api/4004

### Gauti viena skelbima
GET http://localhost:3000/api/ads/1

### Sukurti skelbima
POST http://localhost:3000/api/ads
Content-Type: application/json

{
  "title": "Parduodu vaikišką lovytę",
  "description": "Lovyte beveik kaip nauja, yra keli įbrėžimai",
  "price": 40,
  "phone": "+3709998889",
  "TYPE": "sell",
  "town": "Kaunas",
  "category": "Autobobiliai"
}


### Istrinti viena skelbima
DELETE http://localhost:3000/api/ads/2
