### Sukurti useri
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "NAME": "James Bond",
  "email": "james@bond77.com",
  "PASSWORD": "123456",
  "avatar_url": "https://example.com/avatar4.jpg"
}

### Priloginti useri
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "james@bond77.com",
  "PASSWORD": "123456"
}

### Gauti useri
GET http://localhost:3000/api/users/1

